### ISSUE TITLE
Проблема с выставлением ордеров типа стоп и стоп-лимит

### ISSUE THREAD

**Issue by KonstantinMedvedev1996** [cia76/BackTraderAlor#3]
Игорь, доброго времени суток

В процессе изучения скрипта LimitCancel.Py при попытке выставления ордеров по типу стоп и стоп-лимит возникает следующуя ошибка _**ALBroker - WARNING - Постановка заявки по тикеру AutoOrderedDict().SiM4 на бирже MOEX отклонена. Ошибка веб сервиса.** Ордера по типу лимитный и рыночный без проблем принимаются сервером Alorа.
Прикладываю два лога с успешной постановкой ордера и с отклоненным ордером, а так же сам скрипт с изменненым типом ордера на стоп-лимит

[LimitCancel_(fail_on_limit_order).log](https://github.com/cia76/BackTraderAlor/files/15320346/LimitCancel_.fail_on_limit_order.log)
[LimitCancel_(success_on_limit_order).log](https://github.com/cia76/BackTraderAlor/files/15320351/LimitCancel_.success_on_limit_order.log)
[LimitCancel.txt](https://github.com/cia76/BackTraderAlor/files/15320478/LimitCancel.txt)

**Comment by cia76** [comment]
Константин, добрый день!

Из лога:

15.05.2024 13:37:05 - BackTraderAlor.LimitCancel - INFO - Заявка 1 - Покупка RFUD.SBRF-6.24 -1 @ 32261.13 cоздана и отправлена на биржу MOEX
15.05.2024 13:37:05 - BackTraderAlor.LimitCancel - INFO - Заявка 1 на бирже MOEX со статусом Submitted
15.05.2024 13:37:05 - BackTraderAlor.LimitCancel - INFO - Заявка 1 на бирже MOEX отменена со статусом Rejected

Вы отправляете цену 32261.13 У SBRF-6.24 в спецификации сказано, что десятичных знаков быть не должно. Я знал, что такие ошибки будут, поэтому перед постановкой заявки привожу цену к допустимой через price_to_alor_price.

Далее, уже у себя в коде обнаружил, что сейчас требуется указывать код режима торгов при выставлении стоп заявок. Я внес исправления в код. Сейчас стоп заявки должны выставляться/сниматься/исполняться корректно. Внес исправления в код.

Будьте добры, скачайте последнюю версию BackTraderAlor, протестируйте, и отпишитесь сюда, пропала ли ошибка.

**Comment by KonstantinMedvedev1996** [comment]
Игорь, добрый день!
Огромное спасибо за оперативное решение моего вопроса по работе со стоп-ордерами. Сейчас стопы выводятся на рынок просто идеально. 
Хотел бы отдельно выразить благодарность за все Ваши труды по развитию алготрейдинга среди физиков. В свое время еще Ваши стримы по Wealth-Lab вдохновили меня перейти с ручной  на роботизированную торговлю.
