### ISSUE TITLE
Привет

### ISSUE THREAD

**Issue by nonamegithub** [cia76/BackTraderAlor#4]
Здорово, коллега! Искал репозиторий Алора - вышел на твой. Рад видеть тебя! Если помнишь меня, конечно)

**Comment by cia76** [comment]
Добрый день! Рад всем, кому не безразличен алготрейдинг. Делаю и выкладываю бесплатно то, что многие трейдеры даже за деньги не готовы отдавать. Поэтому, очень много трейдеров тусуются с нами в "Финансовой Лаборатории". К сожалению, всех не упомнить. Если напомните, какие темы и когда мы обсуждали, то освежу свою память.

**Comment by nonamegithub** [comment]
В тиньковском репозитории по свечам и стоп-заявкам чего-то обсуждали...

**Comment by cia76** [comment]
Понял. Если что, то у меня здесь бесплатные репозитории по Квику/Алору/Финаму/Тинькофф. Пользуйтесь на здоровье!
